name: Java Deploy to server

on:
  push:
    branches:
      - main

env:
  application_properties: ${{ secrets.APP_PROPERTIES }}
  jarFileName: messages-0.0.1-SNAPSHOT.jar
  folder_project: sc-admin
  PORT: 8091

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Config application.yml
        run: |
          echo "${{ env.application_properties }}" > ./src/main/resources/application.yml

      - name: Maven Install and Publish Package
        run: |
          ./mvnw install --file pom.xml
          echo "Comprimiendo archivos..."
          tar -czf ${{ env.folder_project }}.tgz target/${{ env.jarFileName }}

      - name: Load to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          server: ${{ secrets.SERVER_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: '${{ env.folder_project }}.tgz'
          remote_path: 'backend/${{ env.folder_project }}'
          sftpArgs: '-o ConnectTimeout=5'

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/backend/${{ env.folder_project }}
            echo "Deteniendo proceso..."
            kill -9 $(lsof -t -i:${{ env.PORT }}) || true
            sleep 5
            echo "Descomprimiendo archivos..."
            tar -xzf ${{ env.folder_project }}.tgz --strip-components=1
            rm ${{ env.folder_project }}.tgz
            echo "Iniciando proceso..."
            java -jar ~/backend/${{ env.folder_project }}/${{ env.jarFileName }} > ~/backend/${{ env.folder_project }}/log.txt 2>&1 &
